/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.cs61b.hw0;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;


class AppTest {
    @Test void testCase1() {
        assertEquals(0, 0);
    }
}
