/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.cs61b.hw0;

import com.cs61b.exercises.ListExercises;
import com.cs61b.exercises.MapExercises;

public class App {
    public static void main(String[] args) {
    }
}
